### ISSUE TITLE
Flutter 3 "Activity? but Activity was expected" bug

### ISSUE THREAD

**Issue by gizemgizg** [xx-li/disable_screenshots#5]
Hello, first of all, thank you very much for the package you developed. When importing Build I get an error that it should be "Activity? but Activity was expected". Can you help me?
<img width="1357" alt="Ekran Resmi 2022-07-03 01 12 18" src="https://user-images.githubusercontent.com/64318805/177017608-f7da6bb3-5c04-4069-8d7c-908c31841358.png">

**Comment by awnigharbia** [comment]
Hey @gizemgizg I got the same issue and solve it.

you can use my fork isntead in your `pubspec.yaml` like this:

```
disable_screenshots: 
    git:
      url: https://github.com/awnigharbia/disable_screenshots.git
      ref: master
```
